name: CI/CD - FastAPI Lab
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: app
        run: pytest -v

  deploy:
    name: Deploy to Amazon Linux server via SSM
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy via SSM Run Command
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy fastapi-cicd-lab" \
            --parameters '{"commands":[
              "if ! systemctl list-unit-files | grep -q api.service; then echo \"=== First time setup ===\" && sudo dnf install -y python3 python3-pip git && cd /home/ec2-user && git clone https://github.com/khanhecate/fastapi-cicd-lab.git && cd fastapi-cicd-lab/app && python3 -m venv venv && source venv/bin/activate && pip install --upgrade pip && pip Install -r requirements.txt && deactivate && sudo cp /home/ec2-user/fastapi-cicd-lab/deploy/api.service /etc/systemd/system/api.service && sudo systemctl daemon-reload && sudo systemctl enable api && sudo systemctl start api; else echo \"=== Updating existing deployment ===\" && export HOME=/root && git config --global --add safe.directory /home/ec2-user/fastapi-cicd-lab && cd /home/ec2-user/fastapi-cicd-lab && git pull origin main && cd app && source venv/bin/activate && pip install -r requirements.txt && deactivate && sudo systemctl restart api; fi" ]}' \ 
            --output text